
var h;h||(h=typeof Module !== 'undefined' ? Module : {});var ba=Object.assign;h.Ge||(h.Ge=0);h.Ge++;
h.ENVIRONMENT_IS_PTHREAD||function(a){function b(n,r,p,t){if("object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)require("fs").readFile(n,function(v,z){v?t(v):p(z.buffer)});else{var u=new XMLHttpRequest;u.open("GET",n,!0);u.responseType="arraybuffer";u.onprogress=function(v){var z=r;v.total&&(z=v.total);if(v.loaded){u.Zd?h.ne[n].loaded=v.loaded:(u.Zd=!0,h.ne||(h.ne={}),h.ne[n]={loaded:v.loaded,total:z});var B=z=v=0,D;for(D in h.ne){var aa=h.ne[D];
v+=aa.total;z+=aa.loaded;B++}v=Math.ceil(v*h.Ge/B);h.setStatus&&h.setStatus("Downloading data... ("+z+"/"+v+")")}else!h.ne&&h.setStatus&&h.setStatus("Downloading data...")};u.onerror=function(){throw Error("NetworkError for: "+n);};u.onload=function(){if(200==u.status||304==u.status||206==u.status||0==u.status&&u.response)p(u.response);else throw Error(u.statusText+" : "+u.responseURL);};u.send(null)}}function c(n){console.error("package error:",n)}function d(){function n(u,v,z){this.start=u;this.end=
v;this.audio=z}function r(u){if(!u)throw"Loading data file failed."+Error().stack;if(!(u instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;u=new Uint8Array(u);n.prototype.Pe=u;u=a.files;for(var v=0;v<u.length;++v)n.prototype.Zd[u[v].filename].onload();h.removeRunDependency("datafile_wasm_out/tetris.data")}h.FS_createPath("/","assets",!0,!0);h.FS_createPath("/assets","effects",!0,!0);h.FS_createPath("/assets","textures",!0,!0);n.prototype={Zd:{},open:function(u,v){this.name=
v;this.Zd[v]=this;h.addRunDependency("fp "+this.name)},send:function(){},onload:function(){this.re(this.Pe.subarray(this.start,this.end))},re:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency("fp "+this.name);this.Zd[this.name]=null}};for(var p=a.files,t=0;t<p.length;++t)(new n(p[t].start,p[t].end,p[t].audio||0)).open("GET",p[t].filename);h.addRunDependency("datafile_wasm_out/tetris.data");h.lf||(h.lf={});h.lf["wasm_out/tetris.data"]={Wf:!1};m?(r(m),m=null):g=r}"object"===
typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));
var e=h.locateFile?h.locateFile("tetris.data",""):"tetris.data",f=a.remote_package_size,g=null,m=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;m||b(e,f,function(n){g?(g(n),g=null):m=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/assets/effects/ePiecesDown.wav",start:0,end:24422,audio:1},{filename:"/assets/effects/eScore.wav",start:24422,end:52034,audio:1},{filename:"/assets/effects/eRotate.wav",start:52034,end:74612,audio:1},{filename:"/assets/textures/numbers.png",
start:74612,end:75307},{filename:"/assets/textures/background.png",start:75307,end:76503},{filename:"/assets/textures/pixels.png",start:76503,end:77154}],remote_package_size:77154,package_uuid:"3bb289d1-a4d4-434a-887c-5edfbfd57b40"});var ca=ba({},h),da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="object"===typeof window,ia="function"===typeof importScripts,ja="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,ka=!ha&&!ja&&!ia,la="";
function ma(a){return h.locateFile?h.locateFile(a,la):la+a}var na,pa,qa,ra,fs,sa,ta;
if(ja)la=ia?require("path").dirname(la)+"/":__dirname+"/",ta=function(){sa||(fs=require("fs"),sa=require("path"))},na=function(a,b){ta();a=sa.normalize(a);return fs.readFileSync(a,b?null:"utf8")},qa=function(a){a=na(a,!0);a.buffer||(a=new Uint8Array(a));return a},pa=function(a,b,c){ta();a=sa.normalize(a);fs.readFile(a,function(d,e){d?c(d):b(e.buffer)})},1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/")),da=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=h),process.on("uncaughtException",
function(a){if(!(a instanceof ua))throw a;}),process.on("unhandledRejection",function(a){throw a;}),fa=(a,b)=>{if(noExitRuntime||0<va)throw process.exitCode=a,b;b instanceof ua||k("exiting due to exception: "+b);process.exit(a)},h.inspect=function(){return"[Emscripten Module object]"},"undefined"===typeof WebAssembly&&(ta(),eval(fs.readFileSync(ma("tetris.wasm.js"))+""));else if(ha||ia)ia?la=self.location.href:"undefined"!==typeof document&&document.currentScript&&(la=document.currentScript.src),
la=0!==la.indexOf("blob:")?la.substr(0,la.replace(/[?#].*/,"").lastIndexOf("/")+1):"",na=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ia&&(qa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),pa=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=
c;d.send(null)},ra=a=>{document.title=a};var wa=h.print||console.log.bind(console),k=h.printErr||console.warn.bind(console);ba(h,ca);ca=null;h.arguments&&(da=h.arguments);h.thisProgram&&(ea=h.thisProgram);h.quit&&(fa=h.quit);function xa(a){ya||(ya={});ya[a]||(ya[a]=1,k(a))}var ya,za=0,Aa;h.wasmBinary&&(Aa=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;
function Ba(a,b){var c="float";"*"===c.charAt(c.length-1)&&(c="i32");switch(c){case "i1":l[a>>0]=b;break;case "i8":l[a>>0]=b;break;case "i16":Ca[a>>1]=b;break;case "i32":q[a>>2]=b;break;case "i64":Da=[b>>>0,(w=b,1<=+Math.abs(w)?0<w?(Math.min(+Math.floor(w/4294967296),4294967295)|0)>>>0:~~+Math.ceil((w-+(~~w>>>0))/4294967296)>>>0:0)];q[a>>2]=Da[0];q[a+4>>2]=Da[1];break;case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;default:A("invalid type for setValue: "+c)}}
var Ea,Fa=!1,Ga,Ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ia(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ha)return Ha.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Ja(a,b){return a?Ia(C,a,b):""}
function Ka(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var m=a.charCodeAt(++f);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}function E(a,b,c){return Ka(a,C,b,c)}
function La(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ma(a){var b=La(a)+1,c=F(b);c&&Ka(a,l,c,b);return c}function Na(a){var b=La(a)+1,c=Oa(b);Ka(a,l,c,b);return c}var Pa,l,C,Ca,Qa,q,Ra,x,y;
function Sa(a){Pa=a;h.HEAP8=l=new Int8Array(a);h.HEAP16=Ca=new Int16Array(a);h.HEAP32=q=new Int32Array(a);h.HEAPU8=C=new Uint8Array(a);h.HEAPU16=Qa=new Uint16Array(a);h.HEAPU32=Ra=new Uint32Array(a);h.HEAPF32=x=new Float32Array(a);h.HEAPF64=y=new Float64Array(a)}var Ta=h.INITIAL_MEMORY||16777216;h.wasmMemory?Ea=h.wasmMemory:Ea=new WebAssembly.Memory({initial:Ta/65536,maximum:32768});Ea&&(Pa=Ea.buffer);Ta=Pa.byteLength;Sa(Pa);var Ua,Va=[],Wa=[],Xa=[],Ya=[],Za=[],$a=!1,va=0;
function ab(){var a=h.preRun.shift();Va.unshift(a)}var bb=0,cb=null,db=null;function eb(){bb++;h.monitorRunDependencies&&h.monitorRunDependencies(bb)}function fb(){bb--;h.monitorRunDependencies&&h.monitorRunDependencies(bb);if(0==bb&&(null!==cb&&(clearInterval(cb),cb=null),db)){var a=db;db=null;a()}}h.preloadedImages={};h.preloadedAudios={};
function A(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);Fa=!0;Ga=1;throw new WebAssembly.RuntimeError(a+". Build with -s ASSERTIONS=1 for more info.");}var gb="tetris.html.mem";function hb(a){return a.startsWith("data:application/octet-stream;base64,")}var G;G="tetris.wasm";hb(G)||(G=ma(G));function ib(){var a=G;try{if(a==G&&Aa)return new Uint8Array(Aa);if(qa)return qa(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function jb(){if(!Aa&&(ha||ia)){if("function"===typeof fetch&&!G.startsWith("file://"))return fetch(G,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+G+"'";return a.arrayBuffer()}).catch(function(){return ib()});if(pa)return new Promise(function(a,b){pa(G,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return ib()})}
var w,Da,nb={90272:function(a){a=Ja(a)+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");a=kb(a);var b=F(a.length);a.subarray||a.slice?C.set(a,b):C.set(new Uint8Array(a),b);return b},90497:function(){return"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?1:0},90634:function(){return"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?
1:0},90858:function(a){"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.Xd||("undefined"!==typeof AudioContext?b.Xd=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.Xd=new webkitAudioContext),b.Xd&&lb(b.Xd));return void 0===b.Xd?-1:0},91351:function(){return h.SDL2.Xd.sampleRate},91419:function(a,b,c,d){function e(){}function f(m){void 0!==g.capture.te&&(clearTimeout(g.capture.te),g.capture.te=void 0);g.capture.Ae=g.Xd.createMediaStreamSource(m);g.capture.$d=
g.Xd.createScriptProcessor(b,a,1);g.capture.$d.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.Fe=n.inputBuffer,mb(c,[d]))};g.capture.Ae.connect(g.capture.$d);g.capture.$d.connect(g.Xd.destination);g.capture.stream=m}var g=h.SDL2;g.capture.De=g.Xd.createBuffer(a,b,g.Xd.sampleRate);g.capture.De.getChannelData(0).fill(0);g.capture.te=setTimeout(function(){g.capture.Fe=g.capture.De;mb(c,[d])},b/g.Xd.sampleRate*1E3);void 0!==navigator.mediaDevices&&
void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},93071:function(a,b,c,d){var e=h.SDL2;e.audio.$d=e.Xd.createScriptProcessor(b,0,a);e.audio.$d.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Ve=f.outputBuffer,mb(c,[d]))};e.audio.$d.connect(e.Xd.destination)},93481:function(a,b){for(var c=h.SDL2,d=c.capture.Fe.numberOfChannels,
e=0;e<d;++e){var f=c.capture.Fe.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ba(a+4*g,f[g]);else for(g=0;g<b;++g)Ba(a+4*(g*d+e),f[g])}},94086:function(a,b){for(var c=h.SDL2,d=c.audio.Ve.numberOfChannels,e=0;e<d;++e){var f=c.audio.Ve.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";
for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},94566:function(a){var b=h.SDL2;if(a){void 0!==b.capture.te&&clearTimeout(b.capture.te);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.$d&&(b.capture.$d.onaudioprocess=function(){},b.capture.$d.disconnect(),b.capture.$d=void 0);void 0!==b.capture.Ae&&(b.capture.Ae.disconnect(),b.capture.Ae=void 0);void 0!==b.capture.De&&(b.capture.De=
void 0);b.capture=void 0}else void 0!=b.audio.$d&&(b.audio.$d.disconnect(),b.audio.$d=void 0),b.audio=void 0;void 0!==b.Xd&&void 0===b.audio&&void 0===b.capture&&(b.Xd.close(),b.Xd=void 0)},95738:function(a,b,c){h.SDL2||(h.SDL2={});var d=h.SDL2;d.sf!==h.canvas&&(d.fe=h.createContext(h.canvas,!1,!0),d.sf=h.canvas);if(d.w!==a||d.Cf!==b||d.Ef!==d.fe)d.image=d.fe.createImageData(a,b),d.w=a,d.Cf=b,d.Ef=d.fe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=
a.length;e<c;){var f=q[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.vf!==a&&(d.uf=new Int32Array(a.buffer),d.wf=new Uint8Array(a.buffer),d.vf=a),a=d.uf,c=a.length,a.set(q.subarray(b,b+c)),a=d.wf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.fe.putImageData(d.image,0,0);return 0},97217:function(a,b,c,d,e){var f=document.createElement("canvas");
f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=q[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(q.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=F(c.length+1);E(c,d,c.length+1);return d},98206:function(a){h.canvas&&
(h.canvas.style.cursor=Ja(a));return 0},98299:function(){h.canvas&&(h.canvas.style.cursor="none")},98368:function(){return window.innerWidth},98398:function(){return window.innerHeight}};function ob(a,b,c){a.addEventListener(b,c,{once:!0})}function lb(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(function(c){b.forEach(function(d){d&&ob(d,c,function(){"suspended"===a.state&&a.resume()})})})}
function pb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(h);else{var c=b.Bf;"number"===typeof c?void 0===b.ve?H(c)():H(c)(b.ve):c(void 0===b.ve?null:b.ve)}}}function qb(a){var b=I();a=a();J(b);return a}var rb=[];function H(a){var b=rb[a];b||(a>=rb.length&&(rb.length=a+1),rb[a]=b=Ua.get(a));return b}function mb(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else H(a).apply(null,b)}
function sb(a){a instanceof ua||"unwind"==a||fa(1,a)}function tb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function ub(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=tb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function vb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function wb(a){if("/"===a)return"/";a=ub(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function xb(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(ja)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){A("randomDevice")}}
function yb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=tb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var zb=[];function Ab(a,b){zb[a]={input:[],output:[],pe:b};Bb(a,Cb)}
var Cb={open:function(a){var b=zb[a.node.rdev];if(!b)throw new L(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.pe.flush(a.tty)},flush:function(a){a.tty.pe.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.pe.Ze)throw new L(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.pe.Ze(a.tty)}catch(m){throw new L(29);}if(void 0===g&&0===e)throw new L(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.pe.Ke)throw new L(60);
try{for(var e=0;e<d;e++)a.tty.pe.Ke(a.tty,b[c+e])}catch(f){throw new L(29);}d&&(a.node.timestamp=Date.now());return e}},Db={Ze:function(a){if(!a.input.length){var b=null;if(ja){var c=Buffer.alloc(256),d=0;try{d=fs.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(e.toString().includes("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=
readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=kb(b,!0)}return a.input.shift()},Ke:function(a,b){null===b||10===b?(wa(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(wa(Ia(a.output,0)),a.output=[])}},Eb={Ke:function(a,b){null===b||10===b?(k(Ia(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(k(Ia(a.output,0)),a.output=[])}},M={ge:null,he:function(){return M.createNode(null,"/",16895,0)},
createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new L(63);M.ge||(M.ge={dir:{node:{ke:M.Ud.ke,ae:M.Ud.ae,lookup:M.Ud.lookup,Be:M.Ud.Be,rename:M.Ud.rename,unlink:M.Ud.unlink,rmdir:M.Ud.rmdir,readdir:M.Ud.readdir,symlink:M.Ud.symlink},stream:{me:M.Vd.me}},file:{node:{ke:M.Ud.ke,ae:M.Ud.ae},stream:{me:M.Vd.me,read:M.Vd.read,write:M.Vd.write,Qe:M.Vd.Qe,ef:M.Vd.ef,gf:M.Vd.gf}},link:{node:{ke:M.Ud.ke,ae:M.Ud.ae,readlink:M.Ud.readlink},stream:{}},Ue:{node:{ke:M.Ud.ke,ae:M.Ud.ae},
stream:Fb}});c=Gb(a,b,c,d);16384===(c.mode&61440)?(c.Ud=M.ge.dir.node,c.Vd=M.ge.dir.stream,c.Td={}):32768===(c.mode&61440)?(c.Ud=M.ge.file.node,c.Vd=M.ge.file.stream,c.Wd=0,c.Td=null):40960===(c.mode&61440)?(c.Ud=M.ge.link.node,c.Vd=M.ge.link.stream):8192===(c.mode&61440)&&(c.Ud=M.ge.Ue.node,c.Vd=M.ge.Ue.stream);c.timestamp=Date.now();a&&(a.Td[b]=c,a.timestamp=c.timestamp);return c},Xf:function(a){return a.Td?a.Td.subarray?a.Td.subarray(0,a.Wd):new Uint8Array(a.Td):new Uint8Array(0)},We:function(a,
b){var c=a.Td?a.Td.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Td,a.Td=new Uint8Array(b),0<a.Wd&&a.Td.set(c.subarray(0,a.Wd),0))},Lf:function(a,b){if(a.Wd!=b)if(0==b)a.Td=null,a.Wd=0;else{var c=a.Td;a.Td=new Uint8Array(b);c&&a.Td.set(c.subarray(0,Math.min(b,a.Wd)));a.Wd=b}},Ud:{ke:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?
b.size=a.Wd:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.rf=4096;b.blocks=Math.ceil(b.size/b.rf);return b},ae:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&M.Lf(a,b.size)},lookup:function(){throw Hb[44];},Be:function(a,b,c,d){return M.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Ib(b,c)}catch(f){}if(d)for(var e in d.Td)throw new L(55);
}delete a.parent.Td[a.name];a.parent.timestamp=Date.now();a.name=c;b.Td[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},unlink:function(a,b){delete a.Td[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=Ib(a,b),d;for(d in c.Td)throw new L(55);delete a.Td[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.Td)a.Td.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=M.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new L(28);
return a.link}},Vd:{read:function(a,b,c,d,e){var f=a.node.Td;if(e>=a.node.Wd)return 0;a=Math.min(a.node.Wd-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===l.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Td||a.Td.subarray)){if(f)return a.Td=b.subarray(c,c+d),a.Wd=d;if(0===a.Wd&&0===e)return a.Td=b.slice(c,c+d),a.Wd=d;if(e+d<=a.Wd)return a.Td.set(b.subarray(c,c+d),e),d}M.We(a,e+
d);if(a.Td.subarray&&b.subarray)a.Td.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Td[e+f]=b[c+f];a.Wd=Math.max(a.Wd,e+d);return d},me:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Wd);if(0>b)throw new L(28);return b},Qe:function(a,b,c){M.We(a.node,b+c);a.node.Wd=Math.max(a.node.Wd,b+c)},ef:function(a,b,c,d,e,f){if(0!==b)throw new L(28);if(32768!==(a.node.mode&61440))throw new L(43);a=a.node.Td;if(f&2||a.buffer!==Pa){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,
d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;A();c=void 0;if(!c)throw new L(48);l.set(a,c)}else d=!1,c=a.byteOffset;return{dg:c,Sf:d}},gf:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new L(43);if(e&2)return 0;M.Vd.write(a,b,0,d,c,!1);return 0}}};function Jb(a,b,c){var d="al "+a;pa(a,function(e){e||A('Loading data file "'+a+'" failed (no arrayBuffer).');b(new Uint8Array(e));d&&fb(d)},function(){if(c)c();else throw'Loading data file "'+a+'" failed.';});d&&eb(d)}
var Kb=null,Lb={},Mb=[],Nb=1,Ob=null,Pb=!0,L=null,Hb={};
function Qb(a,b){a=yb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Xe:!0,Le:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Le)throw new L(32);a=tb(a.split("/").filter(function(g){return!!g}),!1);var e=Kb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Ib(e,a[d]);c=ub(c+"/"+a[d]);e.se&&(!f||f&&b.Xe)&&(e=e.se.root);if(!f||b.He)for(f=0;40960===(e.mode&61440);)if(e=Rb(c),c=yb(vb(c),e),e=Qb(c,{Le:b.Le}).node,40<f++)throw new L(32);}return{path:c,node:e}}
function Sb(a){for(var b;;){if(a===a.parent)return a=a.he.ff,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Tb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Ob.length}function Ib(a,b){var c;if(c=(c=Ub(a,"x"))?c:a.Ud.lookup?0:2)throw new L(c,a);for(c=Ob[Tb(a.id,b)];c;c=c.oe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ud.lookup(a,b)}
function Gb(a,b,c,d){a=new Vb(a,b,c,d);b=Tb(a.parent.id,a.name);a.oe=Ob[b];return Ob[b]=a}var Wb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function Xb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ub(a,b){if(Pb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Yb(a,b){try{return Ib(a,b),20}catch(c){}return Ub(a,"wx")}
function Zb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Mb[a])return a;throw new L(33);}function $b(a,b){ac||(ac=function(){},ac.prototype={});var c=new ac,d;for(d in a)c[d]=a[d];a=c;b=Zb(b);a.fd=b;return Mb[b]=a}var Fb={open:function(a){a.Vd=Lb[a.node.rdev].Vd;a.Vd.open&&a.Vd.open(a)},me:function(){throw new L(70);}};function Bb(a,b){Lb[a]={Vd:b}}
function bc(a,b){var c="/"===b,d=!b;if(c&&Kb)throw new L(10);if(!c&&!d){var e=Qb(b,{Xe:!1});b=e.path;e=e.node;if(e.se)throw new L(10);if(16384!==(e.mode&61440))throw new L(54);}b={type:a,cg:{},ff:b,Jf:[]};a=a.he(b);a.he=b;b.root=a;c?Kb=a:e&&(e.se=b,e.he&&e.he.Jf.push(b))}function cc(a,b,c){var d=Qb(a,{parent:!0}).node;a=wb(a);if(!a||"."===a||".."===a)throw new L(28);var e=Yb(d,a);if(e)throw new L(e);if(!d.Ud.Be)throw new L(63);return d.Ud.Be(d,a,b,c)}function dc(a){return cc(a,16895,0)}
function ec(a,b,c){"undefined"===typeof c&&(c=b,b=438);return cc(a,b|8192,c)}function fc(a,b){if(!yb(a))throw new L(44);var c=Qb(b,{parent:!0}).node;if(!c)throw new L(44);b=wb(b);var d=Yb(c,b);if(d)throw new L(d);if(!c.Ud.symlink)throw new L(63);c.Ud.symlink(c,b,a)}
function gc(a){var b=Qb(a,{parent:!0}).node;if(!b)throw new L(44);var c=wb(a);a=Ib(b,c);a:{try{var d=Ib(b,c)}catch(f){d=f.je;break a}var e=Ub(b,"wx");d=e?e:16384===(d.mode&61440)?31:0}if(d)throw new L(d);if(!b.Ud.unlink)throw new L(63);if(a.se)throw new L(10);b.Ud.unlink(b,c);b=Tb(a.parent.id,a.name);if(Ob[b]===a)Ob[b]=a.oe;else for(b=Ob[b];b;){if(b.oe===a){b.oe=a.oe;break}b=b.oe}}
function Rb(a){a=Qb(a).node;if(!a)throw new L(44);if(!a.Ud.readlink)throw new L(28);return yb(Sb(a.parent),a.Ud.readlink(a))}function hc(a,b){a="string"===typeof a?Qb(a,{He:!0}).node:a;if(!a.Ud.ae)throw new L(63);a.Ud.ae(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function ic(a,b,c,d){if(""===a)throw new L(44);if("string"===typeof b){var e=Wb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=ub(a);try{f=Qb(a,{He:!(b&131072)}).node}catch(g){}}e=!1;if(b&64)if(f){if(b&128)throw new L(20);}else f=cc(a,c,0),e=!0;if(!f)throw new L(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&16384!==(f.mode&61440))throw new L(54);if(!e&&(c=f?40960===(f.mode&61440)?
32:16384===(f.mode&61440)&&("r"!==Xb(b)||b&512)?31:Ub(f,Xb(b)):44))throw new L(c);if(b&512){c=f;c="string"===typeof c?Qb(c,{He:!0}).node:c;if(!c.Ud.ae)throw new L(63);if(16384===(c.mode&61440))throw new L(31);if(32768!==(c.mode&61440))throw new L(28);if(e=Ub(c,"w"))throw new L(e);c.Ud.ae(c,{size:0,timestamp:Date.now()})}b&=-131713;d=$b({node:f,path:Sb(f),id:f.id,flags:b,mode:f.mode,seekable:!0,position:0,Vd:f.Vd,Ud:f.Ud,Of:[],error:!1},d);d.Vd.open&&d.Vd.open(d);!h.logReadFiles||b&1||(jc||(jc={}),
a in jc||(jc[a]=1));return d}function kc(a){if(null===a.fd)throw new L(8);a.Ie&&(a.Ie=null);try{a.Vd.close&&a.Vd.close(a)}catch(b){throw b;}finally{Mb[a.fd]=null}a.fd=null}function lc(a,b,c){if(null===a.fd)throw new L(8);if(!a.seekable||!a.Vd.me)throw new L(70);if(0!=c&&1!=c&&2!=c)throw new L(28);a.position=a.Vd.me(a,b,c);a.Of=[]}
function mc(a,b,c,d,e,f){if(0>d||0>e)throw new L(28);if(null===a.fd)throw new L(8);if(0===(a.flags&2097155))throw new L(8);if(16384===(a.node.mode&61440))throw new L(31);if(!a.Vd.write)throw new L(28);a.seekable&&a.flags&1024&&lc(a,0,2);var g="undefined"!==typeof e;if(!g)e=a.position;else if(!a.seekable)throw new L(70);b=a.Vd.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function nc(){L||(L=function(a,b){this.node=b;this.Mf=function(c){this.je=c};this.Mf(a);this.message="FS error"},L.prototype=Error(),L.prototype.constructor=L,[44].forEach(function(a){Hb[a]=new L(a);Hb[a].stack="<generic error, no stack>"}))}var oc;function qc(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function rc(a,b){a="string"===typeof a?a:Sb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=ub(a+"/"+c);try{dc(d)}catch(e){}a=d}}return d}
function sc(a,b,c,d){a=ub(("string"===typeof a?a:Sb(a))+"/"+b);c=qc(c,d);return cc(a,(void 0!==c?c:438)&4095|32768,0)}function tc(a,b,c,d,e,f){a=b?ub(("string"===typeof a?a:Sb(a))+"/"+b):a;d=qc(d,e);e=cc(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var g=c.length;b<g;++b)a[b]=c.charCodeAt(b);c=a}hc(e,d|146);a=ic(e,577);mc(a,c,0,c.length,0,f);kc(a);hc(e,d)}return e}
function uc(a,b,c,d){a=ub(("string"===typeof a?a:Sb(a))+"/"+b);b=qc(!!c,!!d);uc.cf||(uc.cf=64);var e=uc.cf++<<8|0;Bb(e,{open:function(f){f.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(f,g,m,n){for(var r=0,p=0;p<n;p++){try{var t=c()}catch(u){throw new L(29);}if(void 0===t&&0===r)throw new L(6);if(null===t||void 0===t)break;r++;g[m+p]=t}r&&(f.node.timestamp=Date.now());return r},write:function(f,g,m,n){for(var r=0;r<n;r++)try{d(g[m+r])}catch(p){throw new L(29);}n&&
(f.node.timestamp=Date.now());return r}});return ec(a,b,e)}function vc(a){if(!(a.Hf||a.If||a.link||a.Td)){if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(na)try{a.Td=kb(na(a.url),!0),a.Wd=a.Td.length}catch(b){throw new L(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function wc(a,b,c,d,e){function f(){this.Je=!1;this.Zd=[]}f.prototype.get=function(p){if(!(p>this.length-1||0>p)){var t=p%this.chunkSize;return this.$e(p/this.chunkSize|0)[t]}};f.prototype.re=function(p){this.$e=p};f.prototype.Se=function(){var p=new XMLHttpRequest;p.open("HEAD",c,!1);p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);var t=Number(p.getResponseHeader("Content-length")),u,v=(u=p.getResponseHeader("Accept-Ranges"))&&
"bytes"===u;p=(u=p.getResponseHeader("Content-Encoding"))&&"gzip"===u;var z=1048576;v||(z=t);var B=this;B.re(function(D){var aa=D*z,oa=(D+1)*z-1;oa=Math.min(oa,t-1);if("undefined"===typeof B.Zd[D]){var pc=B.Zd;if(aa>oa)throw Error("invalid range ("+aa+", "+oa+") or no bytes requested!");if(oa>t-1)throw Error("only "+t+" bytes available! programmer error!");var K=new XMLHttpRequest;K.open("GET",c,!1);t!==z&&K.setRequestHeader("Range","bytes="+aa+"-"+oa);"undefined"!=typeof Uint8Array&&(K.responseType=
"arraybuffer");K.overrideMimeType&&K.overrideMimeType("text/plain; charset=x-user-defined");K.send(null);if(!(200<=K.status&&300>K.status||304===K.status))throw Error("Couldn't load "+c+". Status: "+K.status);aa=void 0!==K.response?new Uint8Array(K.response||[]):kb(K.responseText||"",!0);pc[D]=aa}if("undefined"===typeof B.Zd[D])throw Error("doXHR failed!");return B.Zd[D]});if(p||!t)z=t=1,z=t=this.$e(0).length,wa("LazyFiles on gzip forces download of the whole file when length is accessed");this.qf=
t;this.pf=z;this.Je=!0};if("undefined"!==typeof XMLHttpRequest){if(!ia)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var g=new f;Object.defineProperties(g,{length:{get:function(){this.Je||this.Se();return this.qf}},chunkSize:{get:function(){this.Je||this.Se();return this.pf}}});var m=void 0}else m=c,g=void 0;var n=sc(a,b,d,e);g?n.Td=g:m&&(n.Td=null,n.url=m);Object.defineProperties(n,{Wd:{get:function(){return this.Td.length}}});
var r={};Object.keys(n.Vd).forEach(function(p){var t=n.Vd[p];r[p]=function(){vc(n);return t.apply(null,arguments)}});r.read=function(p,t,u,v,z){vc(n);p=p.node.Td;if(z>=p.length)return 0;v=Math.min(p.length-z,v);if(p.slice)for(var B=0;B<v;B++)t[u+B]=p[z+B];else for(B=0;B<v;B++)t[u+B]=p.get(z+B);return v};n.Vd=r;return n}
function xc(a,b,c,d,e,f,g,m,n,r){function p(v){function z(D){r&&r();m||tc(a,b,D,d,e,n);f&&f();fb(u)}var B=!1;h.preloadPlugins.forEach(function(D){!B&&D.canHandle(t)&&(D.handle(v,t,z,function(){g&&g();fb(u)}),B=!0)});B||z(v)}yc();var t=b?yb(ub(a+"/"+b)):a,u="cp "+t;eb(u);"string"==typeof c?Jb(c,function(v){p(v)},g):p(c)}var zc={},ac,jc,Ac=void 0;function Bc(){Ac+=4;return q[Ac-4>>2]}function Cc(a){a=Mb[a];if(!a)throw new L(8);return a}var Dc;
Dc=ja?()=>{var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:()=>performance.now();
function Ec(a,b){Fc=a;Gc=b;if(Hc)if(Ic||(Ic=!0),0==a)Jc=function(){var d=Math.max(0,Kc+b-Dc())|0;setTimeout(Lc,d)};else if(1==a)Jc=function(){Mc(Lc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);ia?(void 0===h.setImmediates&&(h.setImmediates=[]),h.setImmediates.push(d),postMessage({target:"setimmediate"})):postMessage("setimmediate",
"*")}}Jc=function(){setImmediate(Lc)}}}
function Nc(a,b,c,d,e){function f(){if(g<Oc){if(!(noExitRuntime||0<va))try{Pc(Ga)}catch(m){sb(m)}return!1}return!0}!Hc||A("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Hc=a;Qc=d;var g=Oc;Ic=!1;Lc=function(){if(!Fa)if(0<Rc.length){var m=Date.now(),n=Rc.shift();n.Bf(n.ve);if(Sc){var r=Sc,p=0==r%1?r-1:Math.floor(r);Sc=n.Uf?p:(8*r+(p+.5))/9}wa('main loop blocker "'+
n.name+'" took '+(Date.now()-m)+" ms");h.setStatus&&(m=h.statusMessage||"Please wait...",n=Sc,r=Tc.Vf,n?n<r?h.setStatus(m+" ("+(r-n)+"/"+r+")"):h.setStatus(m):h.setStatus(""));f()&&setTimeout(Lc,0)}else f()&&(Uc=Uc+1|0,1==Fc&&1<Gc&&0!=Uc%Gc?Jc():(0==Fc&&(Kc=Dc()),Fa||h.preMainLoop&&!1===h.preMainLoop()||(Vc(a),h.postMainLoop&&h.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.Kf&&SDL.audio.Kf(),Jc())))};e||(b&&0<b?Ec(0,1E3/b):Ec(1,1),Jc());if(c)throw"unwind";}
function Vc(a){if(!$a&&!Fa)try{a()}catch(b){sb(b)}}function Wc(a){setTimeout(function(){Vc(a)},1E4)}var Ic=!1,Jc=null,Oc=0,Hc=null,Qc=0,Fc=0,Gc=0,Uc=0,Rc=[],Tc={},Kc,Lc,Sc,Xc=!1,Yc=!1,Zc=[];
function yc(){function a(){Yc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!$c){$c=!0;try{ad=!0}catch(c){ad=!1,wa("warning: no blob constructor, cannot create blobs with mimetypes")}bd="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:ad?null:wa("warning: no BlobBuilder");cd="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.hf||"undefined"!==typeof cd||(wa("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.hf=!0);h.preloadPlugins.push({canHandle:function(c){return!h.hf&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=null;if(ad)try{g=new Blob([c],{type:dd(d)}),g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:dd(d)}))}catch(r){xa("Blob constructor present but fails: "+
r+"; falling back to blob builder")}g||(g=new bd,g.append((new Uint8Array(c)).buffer),g=g.getBlob());var m=cd.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||A("Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);h.preloadedImages[d]=r;cd.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{wa("Image "+m+" could not be decoded");f&&f()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.bg&&c.substr(-4)in
{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function g(t){n||(n=!0,h.preloadedAudios[d]=t,e&&e(c))}function m(){n||(n=!0,h.preloadedAudios[d]=new Audio,f&&f())}var n=!1;if(ad){try{var r=new Blob([c],{type:dd(d)})}catch(t){return m()}r=cd.createObjectURL(r);var p=new Audio;p.addEventListener("canplaythrough",function(){g(p)},!1);p.onerror=function(){if(!n){wa("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,v=0,z=0;z<c.length;z++)for(u=
u<<8|c[z],v+=8;6<=v;){var B=u>>v-6&63;v-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==v?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==v&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;g(p)}};p.src=r;Wc(function(){g(p)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
function(c){!Yc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function ed(a,b,c,d){if(b&&h.fe&&a==h.canvas)return h.fe;var e;if(b){var f={antialias:!1,alpha:!1,df:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!==typeof fd&&(e=gd(a,f)))var m=hd[e].ie}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"===typeof N||A("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.fe=m,b&&jd(e),h.Pf=b,Zc.forEach(function(n){n()}),yc());return m}var kd=!1,ld=void 0,md=void 0;
function nd(a,b){function c(){Xc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=od,ld&&d.requestPointerLock(),Xc=!0,md?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=Ra[SDL.screen>>2]|8388608),pd(h.canvas),qd()):pd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),md?("undefined"!=typeof SDL&&(q[SDL.screen>>2]=Ra[SDL.screen>>2]&
-8388609),pd(h.canvas),qd()):pd(d));if(h.onFullScreen)h.onFullScreen(Xc);if(h.onFullscreen)h.onFullscreen(Xc)}ld=a;md=b;"undefined"===typeof ld&&(ld=!0);"undefined"===typeof md&&(md=!1);var d=h.canvas;kd||(kd=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function od(){if(!Xc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var rd=0;function Mc(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===rd)rd=b+1E3/60;else for(;b+2>=rd;)rd+=1E3/60;setTimeout(a,Math.max(rd-b,0))}}
function dd(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var sd=[];function qd(){var a=h.canvas;sd.forEach(function(b){b(a.width,a.height)})}
function pd(a,b,c){b&&c?(a.Qf=b,a.Df=c):(b=a.Qf,c=a.Df);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}md?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var $c,ad,bd,cd,O=12288,td=!1,ud=0,vd=0,wd=0,P={alpha:!1,depth:!1,stencil:!1,antialias:!1},xd={},yd;function zd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,g){b.drawElementsInstancedANGLE(c,d,e,f,g)})}
function Ad(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Bd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Cd=1,Dd=[],Q=[],Ed=[],Fd=[],Gd=[],R=[],Hd=[],hd=[],S=[],Id={},Jd=4;
function T(a){Kd||(Kd=a)}function Ld(a){for(var b=Cd++,c=a.length;c<b;c++)a[c]=null;return b}function gd(a,b){a.Ye||(a.Ye=a.getContext,a.getContext=function(d,e){e=a.Ye(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Md(c,b):0}function Md(a,b){var c=Ld(hd),d={Yf:c,attributes:b,version:b.df,ie:a};a.canvas&&(a.canvas.qe=d);hd[c]=d;("undefined"===typeof b.yf||b.yf)&&Nd(d);return c}function jd(a){Od=hd[a];h.fe=N=Od&&Od.ie}
function Nd(a){a||(a=Od);if(!a.Ff){a.Ff=!0;var b=a.ie;zd(b);Ad(b);Bd(b);b.de=b.getExtension("EXT_disjoint_timer_query");b.ag=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var fd={},Kd,Od,Pd=[],Qd=0;function Rd(){for(var a=Sd.length-1;0<=a;--a)Td(a);Sd=[];U=[]}var U=[];
function Ud(a,b,c){function d(g,m){if(g.length!=m.length)return!1;for(var n in g)if(g[n]!=m[n])return!1;return!0}for(var e in U){var f=U[e];if(f.Ne==a&&d(f.Re,c))return}U.push({Ne:a,kf:b,Re:c});U.sort(function(g,m){return g.kf<m.kf})}function Vd(a){for(var b=0;b<U.length;++b)U[b].Ne==a&&(U.splice(b,1),--b)}function Wd(){if(Qd&&Xd.le)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.Ne.apply(null,b.Re)}}var Sd=[];
function Td(a){var b=Sd[a];b.target.removeEventListener(b.Yd,b.zf,b.be);Sd.splice(a,1)}function V(a){function b(d){++Qd;Xd=a;Wd();a.ee(d);Wd();--Qd}if(a.ce)a.zf=b,a.target.addEventListener(a.Yd,b,a.be),Sd.push(a),Yd||(Ya.push(Rd),Yd=!0);else for(var c=0;c<Sd.length;++c)Sd[c].target==a.target&&Sd[c].Yd==a.Yd&&Td(c--)}function Zd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function $d(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var ae={},Yd,Xd,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne={},oe=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function W(a){a=2<a?Ja(a):a;return oe[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}function pe(a){return qb(function(){var b=Oa(8),c=b+4,d=Oa(a.id.length+1);E(a.id,d,a.id.length+1);if(d=W(d))q[b>>2]=d.width,q[c>>2]=d.height;return[q[b>>2],q[c>>2]]})}function qe(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}
function re(a,b,c){a.Tf?qb(function(){var d=Oa(a.id.length+1);E(a.id,d,a.id.length+1);qe(d,b,c)}):(a.width=b,a.height=c)}
function se(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||document.msFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),re(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=p,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=v,a.style.marginRight=
z,a.style.marginTop=B,a.style.marginBottom=D,document.body.style.margin=aa,document.documentElement.style.overflow=oa,document.body.scroll=pc,a.style.af=K,a.qe&&a.qe.ie.viewport(0,0,d,e),ne.we&&H(ne.we)(37,0,ne.Te))}var c=pe(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,p=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,v=a.style.marginLeft,z=a.style.marginRight,B=a.style.marginTop,D=a.style.marginBottom,
aa=document.body.style.margin,oa=document.documentElement.style.overflow,pc=document.body.scroll,K=a.style.af;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function te(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function ue(a){return 0>oe.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function ve(a,b){if(0!=b.Me||0!=b.Ee){se(a);var c=b.Nf?innerWidth:screen.width,d=b.Nf?innerHeight:screen.height,e=ue(a),f=e.width;e=e.height;var g=pe(a),m=g[0];g=g[1];3==b.Me?(te(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Me&&(c*g<m*d?(f=g*c/m,te(a,(d-f)/2,0),d=f):(f=m*d/g,te(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Af&&(a.style.af="pixelated");
f=2==b.Ee?devicePixelRatio:1;0!=b.Ee&&(c=c*f|0,d=d*f|0,re(a,c,d),a.qe&&a.qe.ie.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return $d()?-3:-1;ne=b;b.we&&H(b.we)(37,0,b.Te);return 0}function we(a){if(a.requestPointerLock)a.requestPointerLock();else if(a.Ce)a.Ce();else return document.body.requestPointerLock||document.body.Ce?-3:-1;return 0}
function xe(a,b){y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+8*c+528>>3]="object"===typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)q[a+4*c+1040>>2]="object"===typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];q[a+1296>>2]=b.connected;q[a+1300>>2]=b.index;q[a+8>>2]=b.axes.length;q[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)}
function ye(a,b,c){(a|0)===a&&(a=Ja(a));a=yb(a);if(a=h.preloadedImages[a]){var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=F(a.width*a.height*4);C.set(d.data,e);q[b>>2]=a.width;q[c>>2]=a.height;return e}return 0}var ze=[];function Ae(a,b,c,d){for(var e=0;e<a;e++){var f=N[c](),g=f&&Ld(d);f?(f.name=g,d[g]=f):T(1282);q[b+4*e>>2]=g}}function Be(a,b,c,d,e,f,g,m){b=Q[b];if(a=N[a](b,c))d=m&&E(a.name,m,d),e&&(q[e>>2]=d),f&&(q[f>>2]=a.size),g&&(q[g>>2]=a.type)}
function Ce(a,b){Ra[a>>2]=b;Ra[a+4>>2]=(b-Ra[a>>2])/4294967296}
function De(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&T(1280);return;case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":T(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:T(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:q[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:l[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){T(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+f+")");return}}break;default:T(1280);k("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:Ce(b,
d);break;case 0:q[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:l[b>>0]=d?1:0}}else T(1281)}function Ee(a){var b=La(a)+1,c=F(b);E(a,c,b);return c}function Fe(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function Ge(a){var b=a.ue,c=a.nf,d;if(!b)for(a.ue=b={},a.mf={},d=0;d<N.getProgramParameter(a,35718);++d){var e=N.getActiveUniform(a,d);var f=e.name;e=e.size;var g=Fe(f);g=0<g?f.slice(0,g):f;var m=a.Oe;a.Oe+=e;c[g]=[e,m];for(f=0;f<e;++f)b[m]=f,a.mf[m++]=g}}
function X(a){var b=N.tf;if(b){var c=b.ue[a];"number"===typeof c&&(b.ue[a]=c=N.getUniformLocation(b,b.mf[a]+(0<c?"["+c+"]":"")));return c}T(1282)}function He(a,b,c,d){if(c)if(a=Q[a],Ge(a),a=N.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else T(1281)}
function Ie(a,b,c,d){if(c)if(a=N.getVertexAttrib(a,b),34975==b)q[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:q[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:q[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:q[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:q[c+4*b>>2]=Math.fround(a[b])}else T(1281)}
function Je(a,b,c,d,e){a-=5120;a=1==a?C:4==a?q:6==a?x:5==a||28922==a?Ra:Qa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=Jd;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)}var Ke=[],Le=[];function Me(a,b){if(!$d())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Qd&&Xd.le?ve(a,b):b.xf?(Ud(ve,1,[a,b]),1):-2:-3:-4}
function Ne(a,b){var c={target:W(2),Yd:"beforeunload",ce:b,ee:function(d){d=d||event;var e=H(b)(28,0,a);e&&(e=Ja(e));if(e)return d.preventDefault(),d.returnValue=e},be:!0};V(c)}function Oe(a,b,c,d,e,f){ce||(ce=F(256));a={target:W(a),Yd:f,ce:d,ee:function(g){g=g||event;var m=g.target.id?g.target.id:"",n=ce;E(Zd(g.target),n+0,128);E(m,n+128,128);H(d)(e,n,b)&&g.preventDefault()},be:c};V(a)}
function Pe(a,b,c,d,e){ee||(ee=F(280));V({target:a,Yd:e,ce:d,ee:function(f){f=f||event;var g=ee,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;q[g>>2]=n;q[g+4>>2]=$d();var r=n?m:de,p=r&&r.id?r.id:"";E(Zd(r),g+8,128);E(p,g+136,128);q[g+264>>2]=r?r.clientWidth:0;q[g+268>>2]=r?r.clientHeight:0;q[g+272>>2]=screen.width;q[g+276>>2]=screen.height;n&&(de=m);H(d)(19,g,b)&&f.preventDefault()},be:c})}
function Qe(a,b,c,d,e){fe||(fe=F(1432));b={target:W(2),le:!0,Yd:e,ce:c,ee:function(f){f=f||event;var g=fe;xe(g,f.gamepad);H(c)(d,g,a)&&f.preventDefault()},be:b};V(b)}
function Re(a,b,c,d,e,f){ge||(ge=F(176));a={target:W(a),le:!0,Yd:f,ce:d,ee:function(g){var m=ge;y[m>>3]=g.timeStamp;var n=m>>2;q[n+2]=g.location;q[n+3]=g.ctrlKey;q[n+4]=g.shiftKey;q[n+5]=g.altKey;q[n+6]=g.metaKey;q[n+7]=g.repeat;q[n+8]=g.charCode;q[n+9]=g.keyCode;q[n+10]=g.which;E(g.key||"",m+44,32);E(g.code||"",m+76,32);E(g.char||"",m+108,32);E(g.locale||"",m+140,32);H(d)(e,m,b)&&g.preventDefault()},be:c};V(a)}
function Se(a,b,c){y[a>>3]=b.timeStamp;a>>=2;q[a+2]=b.screenX;q[a+3]=b.screenY;q[a+4]=b.clientX;q[a+5]=b.clientY;q[a+6]=b.ctrlKey;q[a+7]=b.shiftKey;q[a+8]=b.altKey;q[a+9]=b.metaKey;Ca[2*a+20]=b.button;Ca[2*a+21]=b.buttons;q[a+11]=b.movementX;q[a+12]=b.movementY;c=ue(c);q[a+13]=b.clientX-c.left;q[a+14]=b.clientY-c.top}
function Te(a,b,c,d,e,f){he||(he=F(72));a=W(a);V({target:a,le:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Yd:f,ce:d,ee:function(g){g=g||event;Se(he,g,a);H(d)(e,he,b)&&g.preventDefault()},be:c})}function Ue(a,b,c,d,e){ie||(ie=F(260));V({target:a,Yd:e,ce:d,ee:function(f){f=f||event;var g=ie,m=document.pointerLockElement||document.re||document.Rf||document.Pe;q[g>>2]=!!m;var n=m&&m.id?m.id:"";E(Zd(m),g+4,128);E(n,g+132,128);H(d)(20,g,b)&&f.preventDefault()},be:c})}
function Ve(a,b,c,d){je||(je=F(36));a=W(a);V({target:a,Yd:"resize",ce:d,ee:function(e){e=e||event;if(e.target==a){var f=document.body;if(f){var g=je;q[g>>2]=e.detail;q[g+4>>2]=f.clientWidth;q[g+8>>2]=f.clientHeight;q[g+12>>2]=innerWidth;q[g+16>>2]=innerHeight;q[g+20>>2]=outerWidth;q[g+24>>2]=outerHeight;q[g+28>>2]=pageXOffset;q[g+32>>2]=pageYOffset;H(d)(10,g,b)&&e.preventDefault()}}},be:c})}
function We(a,b,c,d,e,f){ke||(ke=F(1696));a=W(a);V({target:a,le:"touchstart"==f||"touchend"==f,Yd:f,ce:d,ee:function(g){for(var m,n={},r=g.touches,p=0;p<r.length;++p)m=r[p],m.bf=m.jf=0,n[m.identifier]=m;for(p=0;p<g.changedTouches.length;++p)m=g.changedTouches[p],m.bf=1,n[m.identifier]=m;for(p=0;p<g.targetTouches.length;++p)n[g.targetTouches[p].identifier].jf=1;r=ke;y[r>>3]=g.timeStamp;var t=r>>2;q[t+3]=g.ctrlKey;q[t+4]=g.shiftKey;q[t+5]=g.altKey;q[t+6]=g.metaKey;t+=7;var u=ue(a),v=0;for(p in n)if(m=
n[p],q[t]=m.identifier,q[t+1]=m.screenX,q[t+2]=m.screenY,q[t+3]=m.clientX,q[t+4]=m.clientY,q[t+5]=m.pageX,q[t+6]=m.pageY,q[t+7]=m.bf,q[t+8]=m.jf,q[t+9]=m.clientX-u.left,q[t+10]=m.clientY-u.top,t+=13,31<++v)break;q[r+8>>2]=v;H(d)(e,r,b)&&g.preventDefault()},be:c})}
function Xe(a,b,c){var d=oe[1];le||(le=F(8));V({target:d,Yd:"visibilitychange",ce:c,ee:function(e){e=e||event;var f=le,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);q[f>>2]=document.hidden;q[f+4>>2]=g;H(c)(21,f,a)&&e.preventDefault()},be:b})}
function Ye(a,b,c,d){me||(me=F(104));V({target:a,le:!0,Yd:"wheel",ce:d,ee:function(e){e=e||event;var f=me;Se(f,e,a);y[f+72>>3]=e.deltaX;y[f+80>>3]=e.deltaY;y[f+88>>3]=e.deltaZ;q[f+96>>2]=e.deltaMode;H(d)(9,f,b)&&e.preventDefault()},be:c})}var Ze={};
function $e(){if(!af){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Ze)void 0===Ze[b]?delete a[b]:a[b]=Ze[b];var c=[];for(b in a)c.push(b+"="+a[b]);af=c}return af}var af;function Vb(a,b,c,d){a||(a=this);this.parent=a;this.he=a.he;this.se=null;this.id=Nb++;this.name=b;this.mode=c;this.Ud={};this.Vd={};this.rdev=d}
Object.defineProperties(Vb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},If:{get:function(){return 16384===(this.mode&61440)}},Hf:{get:function(){return 8192===(this.mode&61440)}}});nc();Ob=Array(4096);bc(M,"/");dc("/tmp");dc("/home");dc("/home/web_user");
(function(){dc("/dev");Bb(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ec("/dev/null",259);Ab(1280,Db);Ab(1536,Eb);ec("/dev/tty",1280);ec("/dev/tty1",1536);var a=xb();uc("/dev","random",a);uc("/dev","urandom",a);dc("/dev/shm");dc("/dev/shm/tmp")})();
(function(){dc("/proc");var a=dc("/proc/self");dc("/proc/self/fd");bc({he:function(){var b=Gb(a,"fd",16895,73);b.Ud={lookup:function(c,d){var e=Mb[+d];if(!e)throw new L(8);c={parent:null,he:{ff:"fake"},Ud:{readlink:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=rc;h.FS_createDataFile=tc;h.FS_createPreloadedFile=xc;h.FS_createLazyFile=wc;h.FS_createDevice=uc;h.FS_unlink=gc;h.requestFullscreen=function(a,b){nd(a,b)};h.requestAnimationFrame=function(a){Mc(a)};
h.setCanvasSize=function(a,b,c){pd(h.canvas,a,b);c||qd()};h.pauseMainLoop=function(){Jc=null;Oc++};h.resumeMainLoop=function(){Oc++;var a=Fc,b=Gc,c=Hc;Hc=null;Nc(c,0,!1,Qc,!0);Ec(a,b);Jc()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return ed(a,b,c,d)};for(var N,Y=0;32>Y;++Y)ze.push(Array(Y));var bf=new Float32Array(288);
for(Y=0;288>Y;++Y)Ke[Y]=bf.subarray(0,Y+1);var cf=new Int32Array(288);for(Y=0;288>Y;++Y)Le[Y]=cf.subarray(0,Y+1);function kb(a,b){var c=Array(La(a)+1);a=Ka(a,c,0,c.length);b&&(c.length=a);return c}
var qf={Q:function(a,b,c){Ac=c;try{var d=Cc(a);switch(b){case 0:var e=Bc();return 0>e?-28:ic(d.path,d.flags,0,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Bc(),d.flags|=e,0;case 5:return e=Bc(),Ca[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return q[df()>>2]=28,-1;default:return-28}}catch(f){if("undefined"===typeof zc||!(f instanceof L))throw f;return-f.je}},ab:function(a,b,c){Ac=c;try{var d=Cc(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?
0:-59;case 21519:if(!d.tty)return-59;var e=Bc();return q[e>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=e=Bc();if(!d.Vd.Gf)throw new L(59);return d.Vd.Gf(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:A("bad ioctl syscall "+b)}}catch(f){if("undefined"===typeof zc||!(f instanceof L))throw f;return-f.je}},bb:function(a,b,c){Ac=c;try{var d=Ja(a),e=c?Bc():0;return ic(d,b,e).fd}catch(f){if("undefined"===typeof zc||!(f instanceof L))throw f;return-f.je}},Xa:function(){throw"longjmp";
},wa:function(){A("")},o:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Dc();else return q[df()>>2]=28,-1;q[b>>2]=a/1E3|0;q[b+4>>2]=a%1E3*1E6|0;return 0},Oa:function(a){if(12448==a)return O=12288,1;O=12300;return 0},Ra:function(a,b,c,d,e){if(62E3!=a)O=12296,c=0;else{if(b)for(;;){a=q[b>>2];if(12321==a)P.alpha=0<q[b+4>>2];else if(12325==a)P.depth=0<q[b+4>>2];else if(12326==a)P.stencil=0<q[b+4>>2];else if(12337==a)a=q[b+4>>2],P.antialias=0<a;else if(12338==a)a=q[b+4>>2],P.antialias=1==a;
else if(12544==a)P.Zf=12547!=q[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(q[e>>2]=1),c&&0<d&&(q[c>>2]=62002),O=12288,c=1):(O=12300,c=0)}return c},Fa:function(a,b,c,d){if(62E3!=a)return O=12296,0;for(a=1;;){b=q[d>>2];if(12440==b)a=q[d+4>>2];else if(12344==b)break;else return O=12292,0;d+=8}if(2!=a)return O=12293,0;P.df=a-1;P.$f=0;yd=gd(h.canvas,P);if(0!=yd)return O=12288,jd(yd),h.Pf=!0,Zc.forEach(function(e){e()}),jd(null),62004;O=12297;return 0},Ha:function(a,b){if(62E3!=a)return O=12296,0;
if(62002!=b)return O=12293,0;O=12288;return 62006},Ga:function(a,b){if(62E3!=a)return O=12296,0;if(62004!=b)return O=12294,0;a=yd;Od===hd[a]&&(Od=null);if("object"===typeof ae)for(var c=hd[a].ie.canvas,d=0;d<Sd.length;++d)Sd[d].target!=c||Td(d--);hd[a]&&hd[a].ie.canvas&&(hd[a].ie.canvas.qe=void 0);hd[a]=null;O=12288;ud==b&&(ud=0);return 1},Ia:function(a,b){if(62E3!=a)return O=12296,0;if(62006!=b)return O=12301,1;vd==b&&(vd=0);wd==b&&(wd=0);O=12288;return 1},Za:function(a,b,c,d){if(62E3!=a)return O=
12296,0;if(62002!=b)return O=12293,0;if(!d)return O=12300,0;O=12288;switch(c){case 12320:return q[d>>2]=P.alpha?32:24,1;case 12321:return q[d>>2]=P.alpha?8:0,1;case 12322:return q[d>>2]=8,1;case 12323:return q[d>>2]=8,1;case 12324:return q[d>>2]=8,1;case 12325:return q[d>>2]=P.depth?24:0,1;case 12326:return q[d>>2]=P.stencil?8:0,1;case 12327:return q[d>>2]=12344,1;case 12328:return q[d>>2]=62002,1;case 12329:return q[d>>2]=0,1;case 12330:return q[d>>2]=4096,1;case 12331:return q[d>>2]=16777216,1;
case 12332:return q[d>>2]=4096,1;case 12333:return q[d>>2]=0,1;case 12334:return q[d>>2]=0,1;case 12335:return q[d>>2]=12344,1;case 12337:return q[d>>2]=P.antialias?4:0,1;case 12338:return q[d>>2]=P.antialias?1:0,1;case 12339:return q[d>>2]=4,1;case 12340:return q[d>>2]=12344,1;case 12341:case 12342:case 12343:return q[d>>2]=-1,1;case 12345:case 12346:return q[d>>2]=0,1;case 12347:return q[d>>2]=0,1;case 12348:return q[d>>2]=1;case 12349:case 12350:return q[d>>2]=0,1;case 12351:return q[d>>2]=12430,
1;case 12352:return q[d>>2]=4,1;case 12354:return q[d>>2]=0,1;default:return O=12292,0}},M:function(){O=12288;return 62E3},Ea:function(){return O},Pa:function(a,b,c){if(62E3==a)return b&&(q[b>>2]=1),c&&(q[c>>2]=4),td=!0,O=12288,1;O=12296;return 0},Ja:function(a,b,c,d){if(62E3!=a)return O=12296,0;if(0!=d&&62004!=d)return O=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return O=12301,0;jd(d?yd:null);ud=d;wd=b;vd=c;O=12288;return 1},Da:function(a,b){if(62E3!=a)return O=12296,0;O=12288;if(xd[b])return xd[b];
switch(b){case 12371:a=Ma("Emscripten");break;case 12372:a=Ma("1.4 Emscripten EGL");break;case 12373:a=Ma("");break;case 12429:a=Ma("OpenGL_ES");break;default:return O=12300,0}return xd[b]=a},Ka:function(){if(td)if(h.fe)if(h.fe.isContextLost())O=12302;else return O=12288,1;else O=12290;else O=12289;return 0},La:function(a,b){if(62E3!=a)return O=12296,0;0==b?Ec(0,0):Ec(1,b);O=12288;return 1},Qa:function(a){if(62E3!=a)return O=12296,0;wd=vd=ud=0;td=!1;O=12288;return 1},Na:function(){O=12288;return 1},
Ma:function(){O=12288;return 1},d:function(a,b,c){Pd.length=0;var d;for(c>>=2;d=C[b++];)(d=105>d)&&c&1&&c++,Pd.push(d?y[c++>>1]:q[c]),++c;return nb[a].apply(null,Pd)},xa:function(){if(!$d())return-1;Vd(ve);var a=oe[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ba:function(){Vd(we);if(document.exitPointerLock)document.exitPointerLock();else if(document.Zd)document.Zd();else return-1;
return 0},h:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},e:function(a,b,c){a=W(a);if(!a)return-4;a=ue(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},T:function(a,b){if(0>a||a>=be.length)return-5;if(!be[a])return-7;xe(b,be[a]);return 0},N:Dc,wc:function(){return be.length},Fd:ye,Jb:function(a,b,c){a=h._fileno(a);return(a=Mb[a])?ye(a.path,b,c):0},Ca:function(a,b){q[a>>2]=screen.width;q[b>>2]=screen.height},ca:function(a){N.activeTexture(a)},ba:function(a,b){N.attachShader(Q[a],
R[b])},sa:function(a,b){N.de.beginQueryEXT(a,S[b])},aa:function(a,b,c){N.bindAttribLocation(Q[a],b,Ja(c))},$:function(a,b){N.bindBuffer(a,Dd[b])},_:function(a,b){N.bindFramebuffer(a,Ed[b])},Z:function(a,b){N.bindRenderbuffer(a,Fd[b])},Y:function(a,b){N.bindTexture(a,Gd[b])},ka:function(a){N.bindVertexArray(Hd[a])},X:function(a,b,c,d){N.blendColor(a,b,c,d)},W:function(a){N.blendEquation(a)},Dd:function(a,b){N.blendEquationSeparate(a,b)},Cd:function(a,b){N.blendFunc(a,b)},Bd:function(a,b,c,d){N.blendFuncSeparate(a,
b,c,d)},Ad:function(a,b,c,d){N.bufferData(a,c?C.subarray(c,c+b):b,d)},zd:function(a,b,c,d){N.bufferSubData(a,b,C.subarray(d,d+c))},yd:function(a){return N.checkFramebufferStatus(a)},xd:function(a){N.clear(a)},wd:function(a,b,c,d){N.clearColor(a,b,c,d)},vd:function(a){N.clearDepth(a)},ud:function(a){N.clearStencil(a)},td:function(a,b,c,d){N.colorMask(!!a,!!b,!!c,!!d)},sd:function(a){N.compileShader(R[a])},rd:function(a,b,c,d,e,f,g,m){N.compressedTexImage2D(a,b,c,d,e,f,m?C.subarray(m,m+g):null)},qd:function(a,
b,c,d,e,f,g,m,n){N.compressedTexSubImage2D(a,b,c,d,e,f,g,n?C.subarray(n,n+m):null)},pd:function(a,b,c,d,e,f,g,m){N.copyTexImage2D(a,b,c,d,e,f,g,m)},od:function(a,b,c,d,e,f,g,m){N.copyTexSubImage2D(a,b,c,d,e,f,g,m)},nd:function(){var a=Ld(Q),b=N.createProgram();b.name=a;b.ze=b.xe=b.ye=0;b.Oe=1;Q[a]=b;return a},md:function(a){var b=Ld(R);R[b]=N.createShader(a);return b},ld:function(a){N.cullFace(a)},kd:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Dd[d];e&&(N.deleteBuffer(e),e.name=0,Dd[d]=
null)}},jd:function(a,b){for(var c=0;c<a;++c){var d=q[b+4*c>>2],e=Ed[d];e&&(N.deleteFramebuffer(e),e.name=0,Ed[d]=null)}},id:function(a){if(a){var b=Q[a];b?(N.deleteProgram(b),b.name=0,Q[a]=null):T(1281)}},ua:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=S[d];e&&(N.de.deleteQueryEXT(e),S[d]=null)}},hd:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Fd[d];e&&(N.deleteRenderbuffer(e),e.name=0,Fd[d]=null)}},gd:function(a){if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T(1281)}},fd:function(a,
b){for(var c=0;c<a;c++){var d=q[b+4*c>>2],e=Gd[d];e&&(N.deleteTexture(e),e.name=0,Gd[d]=null)}},ja:function(a,b){for(var c=0;c<a;c++){var d=q[b+4*c>>2];N.deleteVertexArray(Hd[d]);Hd[d]=null}},ed:function(a){N.depthFunc(a)},dd:function(a){N.depthMask(!!a)},cd:function(a,b){N.depthRange(a,b)},bd:function(a,b){N.detachShader(Q[a],R[b])},ad:function(a){N.disable(a)},_c:function(a){N.disableVertexAttribArray(a)},Zc:function(a,b,c){N.drawArrays(a,b,c)},fa:function(a,b,c,d){N.drawArraysInstanced(a,b,c,d)},
ga:function(a,b){for(var c=ze[a],d=0;d<a;d++)c[d]=q[b+4*d>>2];N.drawBuffers(c)},Yc:function(a,b,c,d){N.drawElements(a,b,c,d)},ea:function(a,b,c,d,e){N.drawElementsInstanced(a,b,c,d,e)},Xc:function(a){N.enable(a)},Wc:function(a){N.enableVertexAttribArray(a)},ra:function(a){N.de.endQueryEXT(a)},Vc:function(){N.finish()},Uc:function(){N.flush()},Tc:function(a,b,c,d){N.framebufferRenderbuffer(a,b,c,Fd[d])},Sc:function(a,b,c,d,e){N.framebufferTexture2D(a,b,c,Gd[d],e)},Rc:function(a){N.frontFace(a)},Qc:function(a,
b){Ae(a,b,"createBuffer",Dd)},Oc:function(a,b){Ae(a,b,"createFramebuffer",Ed)},va:function(a,b){for(var c=0;c<a;c++){var d=N.de.createQueryEXT();if(!d){for(T(1282);c<a;)q[b+4*c++>>2]=0;break}var e=Ld(S);d.name=e;S[e]=d;q[b+4*c>>2]=e}},Nc:function(a,b){Ae(a,b,"createRenderbuffer",Fd)},Mc:function(a,b){Ae(a,b,"createTexture",Gd)},ia:function(a,b){Ae(a,b,"createVertexArray",Hd)},Pc:function(a){N.generateMipmap(a)},Lc:function(a,b,c,d,e,f,g){Be("getActiveAttrib",a,b,c,d,e,f,g)},Kc:function(a,b,c,d,e,
f,g){Be("getActiveUniform",a,b,c,d,e,f,g)},Jc:function(a,b,c,d){a=N.getAttachedShaders(Q[a]);var e=a.length;e>b&&(e=b);q[c>>2]=e;for(b=0;b<e;++b)q[d+4*b>>2]=R.indexOf(a[b])},Ic:function(a,b){return N.getAttribLocation(Q[a],Ja(b))},Hc:function(a,b){De(a,b,4)},Gc:function(a,b,c){c?q[c>>2]=N.getBufferParameter(a,b):T(1281)},Fc:function(){var a=N.getError()||Kd;Kd=0;return a},Ec:function(a,b){De(a,b,2)},Dc:function(a,b,c,d){a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||
a instanceof WebGLTexture)a=a.name|0;q[d>>2]=a},Cc:function(a,b){De(a,b,0)},Ac:function(a,b,c,d){a=N.getProgramInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(q[c>>2]=b)},Bc:function(a,b,c){if(c)if(a>=Cd)T(1281);else if(a=Q[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),q[c>>2]=a.length+1;else if(35719==b){if(!a.ze)for(b=0;b<N.getProgramParameter(a,35718);++b)a.ze=Math.max(a.ze,N.getActiveUniform(a,b).name.length+1);q[c>>2]=a.ze}else if(35722==b){if(!a.xe)for(b=
0;b<N.getProgramParameter(a,35721);++b)a.xe=Math.max(a.xe,N.getActiveAttrib(a,b).name.length+1);q[c>>2]=a.xe}else if(35381==b){if(!a.ye)for(b=0;b<N.getProgramParameter(a,35382);++b)a.ye=Math.max(a.ye,N.getActiveUniformBlockName(a,b).length+1);q[c>>2]=a.ye}else q[c>>2]=N.getProgramParameter(a,b);else T(1281)},ma:function(a,b,c){if(c){a=N.de.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Ce(c,d)}else T(1281)},oa:function(a,b,c){if(c){a=N.de.getQueryObjectEXT(S[a],b);var d;"boolean"==
typeof a?d=a?1:0:d=a;q[c>>2]=d}else T(1281)},la:function(a,b,c){if(c){a=N.de.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;Ce(c,d)}else T(1281)},na:function(a,b,c){if(c){a=N.de.getQueryObjectEXT(S[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;q[c>>2]=d}else T(1281)},pa:function(a,b,c){c?q[c>>2]=N.de.getQueryEXT(a,b):T(1281)},zc:function(a,b,c){c?q[c>>2]=N.getRenderbufferParameter(a,b):T(1281)},xc:function(a,b,c,d){a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?
E(a,d,b):0;c&&(q[c>>2]=b)},vc:function(a,b,c,d){a=N.getShaderPrecisionFormat(a,b);q[c>>2]=a.rangeMin;q[c+4>>2]=a.rangeMax;q[d>>2]=a.precision},uc:function(a,b,c,d){if(a=N.getShaderSource(R[a]))b=0<b&&d?E(a,d,b):0,c&&(q[c>>2]=b)},yc:function(a,b,c){c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),q[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),q[c>>2]=a?a.length+1:0):q[c>>2]=N.getShaderParameter(R[a],b):T(1281)},tc:function(a){var b=Id[a];if(!b){switch(a){case 7939:b=
N.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Ee(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=N.getParameter(a))||T(1280);b=b&&Ee(b);break;case 7938:b=Ee("OpenGL ES 2.0 ("+N.getParameter(7938)+")");break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Ee(b);break;default:T(1280)}Id[a]=b}return b},sc:function(a,b,c){c?
x[c>>2]=N.getTexParameter(a,b):T(1281)},rc:function(a,b,c){c?q[c>>2]=N.getTexParameter(a,b):T(1281)},oc:function(a,b){b=Ja(b);if(a=Q[a]){Ge(a);var c=a.ue,d=0,e=b,f=Fe(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.nf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T(1281);return-1},qc:function(a,b,c){He(a,b,c,2)},pc:function(a,b,c){He(a,b,c,0)},lc:function(a,b,c){c?q[c>>2]=N.getVertexAttribOffset(a,b):T(1281)},nc:function(a,b,c){Ie(a,b,c,2)},mc:function(a,
b,c){Ie(a,b,c,5)},kc:function(a,b){N.hint(a,b)},jc:function(a){return(a=Dd[a])?N.isBuffer(a):0},ic:function(a){return N.isEnabled(a)},hc:function(a){return(a=Ed[a])?N.isFramebuffer(a):0},gc:function(a){return(a=Q[a])?N.isProgram(a):0},ta:function(a){return(a=S[a])?N.de.isQueryEXT(a):0},fc:function(a){return(a=Fd[a])?N.isRenderbuffer(a):0},ec:function(a){return(a=R[a])?N.isShader(a):0},dc:function(a){return(a=Gd[a])?N.isTexture(a):0},ha:function(a){return(a=Hd[a])?N.isVertexArray(a):0},cc:function(a){N.lineWidth(a)},
bc:function(a){a=Q[a];N.linkProgram(a);a.ue=0;a.nf={}},ac:function(a,b){3317==a&&(Jd=b);N.pixelStorei(a,b)},$b:function(a,b){N.polygonOffset(a,b)},qa:function(a,b){N.de.queryCounterEXT(S[a],b)},_b:function(a,b,c,d,e,f,g){(g=Je(f,e,c,d,g))?N.readPixels(a,b,c,d,e,f,g):T(1280)},Zb:function(){},Yb:function(a,b,c,d){N.renderbufferStorage(a,b,c,d)},Xb:function(a,b){N.sampleCoverage(a,!!b)},Wb:function(a,b,c,d){N.scissor(a,b,c,d)},Vb:function(){T(1280)},Ub:function(a,b,c,d){for(var e="",f=0;f<b;++f){var g=
d?q[d+4*f>>2]:-1;e+=Ja(q[c+4*f>>2],0>g?void 0:g)}N.shaderSource(R[a],e)},Tb:function(a,b,c){N.stencilFunc(a,b,c)},Sb:function(a,b,c,d){N.stencilFuncSeparate(a,b,c,d)},Rb:function(a){N.stencilMask(a)},Qb:function(a,b){N.stencilMaskSeparate(a,b)},Pb:function(a,b,c){N.stencilOp(a,b,c)},Ob:function(a,b,c,d){N.stencilOpSeparate(a,b,c,d)},Nb:function(a,b,c,d,e,f,g,m,n){N.texImage2D(a,b,c,d,e,f,g,m,n?Je(m,g,d,e,n):null)},Mb:function(a,b,c){N.texParameterf(a,b,c)},Lb:function(a,b,c){N.texParameterf(a,b,x[c>>
2])},Kb:function(a,b,c){N.texParameteri(a,b,c)},Ib:function(a,b,c){N.texParameteri(a,b,q[c>>2])},Hb:function(a,b,c,d,e,f,g,m,n){var r=null;n&&(r=Je(m,g,e,f,n));N.texSubImage2D(a,b,c,d,e,f,g,m,r)},Gb:function(a,b){N.uniform1f(X(a),b)},Fb:function(a,b,c){if(288>=b)for(var d=Ke[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(X(a),d)},Eb:function(a,b){N.uniform1i(X(a),b)},Db:function(a,b,c){if(288>=b)for(var d=Le[b-1],e=0;e<b;++e)d[e]=q[c+4*e>>2];else d=q.subarray(c>>2,
c+4*b>>2);N.uniform1iv(X(a),d)},Cb:function(a,b,c){N.uniform2f(X(a),b,c)},Bb:function(a,b,c){if(144>=b)for(var d=Ke[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(X(a),d)},Ab:function(a,b,c){N.uniform2i(X(a),b,c)},zb:function(a,b,c){if(144>=b)for(var d=Le[2*b-1],e=0;e<2*b;e+=2)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2];else d=q.subarray(c>>2,c+8*b>>2);N.uniform2iv(X(a),d)},yb:function(a,b,c,d){N.uniform3f(X(a),b,c,d)},xb:function(a,b,c){if(96>=
b)for(var d=Ke[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(X(a),d)},wb:function(a,b,c,d){N.uniform3i(X(a),b,c,d)},vb:function(a,b,c){if(96>=b)for(var d=Le[3*b-1],e=0;e<3*b;e+=3)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2];else d=q.subarray(c>>2,c+12*b>>2);N.uniform3iv(X(a),d)},ub:function(a,b,c,d,e){N.uniform4f(X(a),b,c,d,e)},tb:function(a,b,c){if(72>=b){var d=Ke[4*b-1],e=x;c>>=2;for(var f=0;f<
4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(X(a),d)},sb:function(a,b,c,d,e){N.uniform4i(X(a),b,c,d,e)},rb:function(a,b,c){if(72>=b)for(var d=Le[4*b-1],e=0;e<4*b;e+=4)d[e]=q[c+4*e>>2],d[e+1]=q[c+(4*e+4)>>2],d[e+2]=q[c+(4*e+8)>>2],d[e+3]=q[c+(4*e+12)>>2];else d=q.subarray(c>>2,c+16*b>>2);N.uniform4iv(X(a),d)},qb:function(a,b,c,d){if(72>=b)for(var e=Ke[4*b-1],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+
(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);N.uniformMatrix2fv(X(a),!!c,e)},pb:function(a,b,c,d){if(32>=b)for(var e=Ke[9*b-1],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);N.uniformMatrix3fv(X(a),!!c,e)},ob:function(a,b,c,d){if(18>=b){var e=Ke[16*b-1],f=x;d>>=2;for(var g=
0;g<16*b;g+=16){var m=d+g;e[g]=f[m];e[g+1]=f[m+1];e[g+2]=f[m+2];e[g+3]=f[m+3];e[g+4]=f[m+4];e[g+5]=f[m+5];e[g+6]=f[m+6];e[g+7]=f[m+7];e[g+8]=f[m+8];e[g+9]=f[m+9];e[g+10]=f[m+10];e[g+11]=f[m+11];e[g+12]=f[m+12];e[g+13]=f[m+13];e[g+14]=f[m+14];e[g+15]=f[m+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(X(a),!!c,e)},nb:function(a){a=Q[a];N.useProgram(a);N.tf=a},mb:function(a){N.validateProgram(Q[a])},lb:function(a,b){N.vertexAttrib1f(a,b)},kb:function(a,b){N.vertexAttrib1f(a,x[b>>2])},jb:function(a,
b,c){N.vertexAttrib2f(a,b,c)},ib:function(a,b){N.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},hb:function(a,b,c,d){N.vertexAttrib3f(a,b,c,d)},gb:function(a,b){N.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},fb:function(a,b,c,d,e){N.vertexAttrib4f(a,b,c,d,e)},eb:function(a,b){N.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},da:function(a,b){N.vertexAttribDivisor(a,b)},db:function(a,b,c,d,e,f){N.vertexAttribPointer(a,b,c,!!d,e,f)},cb:function(a,b,c,d){N.viewport(a,b,c,d)},m:function(){return 0},
Va:function(a,b,c){C.copyWithin(a,b,b+c)},ya:function(a,b,c){return Me(a,{Me:q[c>>2],Ee:q[c+4>>2],Af:q[c+8>>2],xf:b,we:q[c+12>>2],Te:q[c+16>>2]})},L:function(a,b){a=W(a);return a?a.requestPointerLock||a.Ce?Qd&&Xd.le?we(a):b?(Ud(we,2,[a]),1):-2:-1:-4},Wa:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{Ea.grow(Math.min(2147483648,d)-Pa.byteLength+65535>>>16);Sa(Ea.buffer);
var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},U:function(){return(be=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},r:function(a,b,c){if("undefined"===typeof onbeforeunload)return-1;if(1!==c)return-5;Ne(a,b);return 0},D:function(a,b,c,d){Oe(a,b,c,d,12,"blur");return 0},g:qe,k:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},E:function(a,b,c,d){Oe(a,b,c,d,13,"focus");return 0},
u:function(a,b,c,d){if(!$d())return-1;a=W(a);if(!a)return-4;Pe(a,b,c,d,"fullscreenchange");Pe(a,b,c,d,"webkitfullscreenchange");return 0},S:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Qe(a,b,c,26,"gamepadconnected");return 0},R:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Qe(a,b,c,27,"gamepaddisconnected");return 0},x:function(a,b,c,d){Re(a,b,c,d,2,"keydown");return 0},v:function(a,b,c,d){Re(a,b,c,d,1,"keypress");return 0},w:function(a,
b,c,d){Re(a,b,c,d,3,"keyup");return 0},Gd:function(a,b,c){a=H(a);Nc(a,b,c)},J:function(a,b,c,d){Te(a,b,c,d,5,"mousedown");return 0},H:function(a,b,c,d){Te(a,b,c,d,33,"mouseenter");return 0},G:function(a,b,c,d){Te(a,b,c,d,34,"mouseleave");return 0},K:function(a,b,c,d){Te(a,b,c,d,8,"mousemove");return 0},I:function(a,b,c,d){Te(a,b,c,d,6,"mouseup");return 0},y:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Zd||document.body.re||document.body.Ce))return-1;
a=W(a);if(!a)return-4;Ue(a,b,c,d,"pointerlockchange");Ue(a,b,c,d,"mozpointerlockchange");Ue(a,b,c,d,"webkitpointerlockchange");Ue(a,b,c,d,"mspointerlockchange");return 0},t:function(a,b,c,d){Ve(a,b,c,d);return 0},z:function(a,b,c,d){We(a,b,c,d,25,"touchcancel");return 0},B:function(a,b,c,d){We(a,b,c,d,23,"touchend");return 0},A:function(a,b,c,d){We(a,b,c,d,24,"touchmove");return 0},C:function(a,b,c,d){We(a,b,c,d,22,"touchstart");return 0},s:function(a,b,c){if(!oe[1])return-4;Xe(a,b,c);return 0},F:function(a,
b,c,d){a=W(a);return"undefined"!==typeof a.onwheel?(Ye(a,b,c,d),0):-1},za:function(a){a:for(var b="";;){var c=C[a++>>0];if(!c)break a;b+=String.fromCharCode(c)}ra(b)},l:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Ya:function(a,b){var c=0;$e().forEach(function(d,e){var f=b+c;e=q[a+4*e>>2]=f;for(f=0;f<d.length;++f)l[e++>>0]=d.charCodeAt(f);l[e>>0]=0;c+=d.length+1});return 0},_a:function(a,b){var c=$e();q[a>>2]=c.length;
var d=0;c.forEach(function(e){d+=e.length+1});q[b>>2]=d;return 0},O:function(a){try{var b=Cc(a);kc(b);return 0}catch(c){if("undefined"===typeof zc||!(c instanceof L))throw c;return c.je}},$a:function(a,b,c,d){try{a:{for(var e=Cc(a),f=a=0;f<c;f++){var g=q[b+(8*f+4)>>2],m=e,n=q[b+8*f>>2],r=g,p=void 0,t=l;if(0>r||0>p)throw new L(28);if(null===m.fd)throw new L(8);if(1===(m.flags&2097155))throw new L(8);if(16384===(m.node.mode&61440))throw new L(31);if(!m.Vd.read)throw new L(28);var u="undefined"!==typeof p;
if(!u)p=m.position;else if(!m.seekable)throw new L(70);var v=m.Vd.read(m,t,n,r,p);u||(m.position+=v);var z=v;if(0>z){var B=-1;break a}a+=z;if(z<g)break}B=a}q[d>>2]=B;return 0}catch(D){if("undefined"===typeof zc||!(D instanceof L))throw D;return D.je}},Sa:function(a,b,c,d,e){try{var f=Cc(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;lc(f,a,d);Da=[f.position>>>0,(w=f.position,1<=+Math.abs(w)?0<w?(Math.min(+Math.floor(w/4294967296),4294967295)|0)>>>0:~~+Math.ceil((w-
+(~~w>>>0))/4294967296)>>>0:0)];q[e>>2]=Da[0];q[e+4>>2]=Da[1];f.Ie&&0===a&&0===d&&(f.Ie=null);return 0}catch(g){if("undefined"===typeof zc||!(g instanceof L))throw g;return g.je}},P:function(a,b,c,d){try{a:{for(var e=Cc(a),f=a=0;f<c;f++){var g=mc(e,l,q[b+8*f>>2],q[b+(8*f+4)>>2],void 0);if(0>g){var m=-1;break a}a+=g}m=a}q[d>>2]=m;return 0}catch(n){if("undefined"===typeof zc||!(n instanceof L))throw n;return n.je}},b:function(){return za},n:function(a){var b=Date.now();q[a>>2]=b/1E3|0;q[a+4>>2]=b%1E3*
1E3|0;return 0},j:ef,p:ff,q:gf,Aa:hf,$c:jf,V:kf,Ua:lf,Ta:mf,f:nf,i:of,Ed:pf,a:Ea,c:function(a){za=a}};
(function(){function a(e){h.asm=e.exports;rf();Ua=h.asm.Jd;Wa.unshift(h.asm.Hd);fb("wasm-instantiate")}function b(e){a(e.instance)}function c(e){return jb().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){k("failed to asynchronously prepare wasm: "+f);if("undefined"!==typeof location){var g=location.search;if(0>g.indexOf("_rwasm=0")){location.href+=(g?g+"&":"?")+"_rwasm=0";return}}A(f)})}var d={a:qf};eb("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(d,
a)}catch(e){return k("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Aa||"function"!==typeof WebAssembly.instantiateStreaming||hb(G)||G.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(G,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){k("wasm streaming compile failed: "+f);k("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
h.___wasm_call_ctors=function(){return(h.___wasm_call_ctors=h.asm.Hd).apply(null,arguments)};h._main=function(){return(h._main=h.asm.Id).apply(null,arguments)};var F=h._malloc=function(){return(F=h._malloc=h.asm.Kd).apply(null,arguments)},df=h.___errno_location=function(){return(df=h.___errno_location=h.asm.Ld).apply(null,arguments)};h._fileno=function(){return(h._fileno=h.asm.Md).apply(null,arguments)};
var Z=h._setThrew=function(){return(Z=h._setThrew=h.asm.Nd).apply(null,arguments)},I=h.stackSave=function(){return(I=h.stackSave=h.asm.Od).apply(null,arguments)},J=h.stackRestore=function(){return(J=h.stackRestore=h.asm.Pd).apply(null,arguments)},Oa=h.stackAlloc=function(){return(Oa=h.stackAlloc=h.asm.Qd).apply(null,arguments)},sf=h.dynCall_ji=function(){return(sf=h.dynCall_ji=h.asm.Rd).apply(null,arguments)},tf=h.dynCall_jiji=function(){return(tf=h.dynCall_jiji=h.asm.Sd).apply(null,arguments)};
function ef(a,b){var c=I();try{return H(a)(b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function hf(a,b,c,d,e){var f=I();try{return H(a)(b,c,d,e)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}function gf(a,b,c,d){var e=I();try{return H(a)(b,c,d)}catch(f){J(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function nf(a,b){var c=I();try{H(a)(b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}
function ff(a,b,c){var d=I();try{return H(a)(b,c)}catch(e){J(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function pf(a,b,c,d){var e=I();try{H(a)(b,c,d)}catch(f){J(e);if(f!==f+0&&"longjmp"!==f)throw f;Z(1,0)}}function of(a,b,c){var d=I();try{H(a)(b,c)}catch(e){J(d);if(e!==e+0&&"longjmp"!==e)throw e;Z(1,0)}}function kf(a,b,c,d,e,f,g,m,n,r){var p=I();try{return H(a)(b,c,d,e,f,g,m,n,r)}catch(t){J(p);if(t!==t+0&&"longjmp"!==t)throw t;Z(1,0)}}
function jf(a,b,c,d,e,f,g,m,n){var r=I();try{return H(a)(b,c,d,e,f,g,m,n)}catch(p){J(r);if(p!==p+0&&"longjmp"!==p)throw p;Z(1,0)}}function lf(a,b){var c=I();try{return sf(a,b)}catch(d){J(c);if(d!==d+0&&"longjmp"!==d)throw d;Z(1,0)}}function mf(a,b,c,d,e){var f=I();try{return tf(a,b,c,d,e)}catch(g){J(f);if(g!==g+0&&"longjmp"!==g)throw g;Z(1,0)}}h.addRunDependency=eb;h.removeRunDependency=fb;h.FS_createPath=rc;h.FS_createDataFile=tc;h.FS_createPreloadedFile=xc;h.FS_createLazyFile=wc;
h.FS_createDevice=uc;h.FS_unlink=gc;
function rf(){if(gb)if(hb(gb)||(gb=ma(gb)),ja||ka){var a=qa(gb);C.set(a,1024)}else{eb("memory initializer");var b=function(d){d.byteLength&&(d=new Uint8Array(d));C.set(d,1024);h.memoryInitializerRequest&&delete h.memoryInitializerRequest.response;fb("memory initializer")},c=function(){pa(gb,b,function(){throw Error("could not load memory initializer "+gb);})};h.memoryInitializerRequest?(a=function(){var d=h.memoryInitializerRequest,e=d.response;200!==d.status&&0!==d.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+
d.status+", retrying "+gb),c()):b(e)},h.memoryInitializerRequest.response?setTimeout(a,0):h.memoryInitializerRequest.addEventListener("load",a)):c()}}var uf;function ua(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}db=function vf(){uf||wf();uf||(db=vf)};
function wf(a){function b(){if(!uf&&(uf=!0,h.calledRun=!0,!Fa)){h.noFSInit||oc||(oc=!0,nc(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?uc("/dev","stdin",h.stdin):fc("/dev/tty","/dev/stdin"),h.stdout?uc("/dev","stdout",null,h.stdout):fc("/dev/tty","/dev/stdout"),h.stderr?uc("/dev","stderr",null,h.stderr):fc("/dev/tty1","/dev/stderr"),ic("/dev/stdin",0),ic("/dev/stdout",1),ic("/dev/stderr",1));Pb=!1;pb(Wa);pb(Xa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();if(xf){var c=a,d=h._main;
c=c||[];var e=c.length+1,f=Oa(4*(e+1));q[f>>2]=Na(ea);for(var g=1;g<e;g++)q[(f>>2)+g]=Na(c[g-1]);q[(f>>2)+e]=0;try{var m=d(e,f);Pc(m)}catch(n){sb(n)}finally{}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)c=h.postRun.shift(),Za.unshift(c);pb(Za)}}a=a||da;if(!(0<bb)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ab();pb(Va);0<bb||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},
1);b()},1)):b())}}h.run=wf;function Pc(a){Ga=a;noExitRuntime||0<va||($a=!0);Ga=a;if(!(noExitRuntime||0<va)){if(h.onExit)h.onExit(a);Fa=!0}fa(a,new ua(a))}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var xf=!0;h.noInitialRun&&(xf=!1);wf();
